### ISSUE TITLE
The settings on this account do not allow you to add comments

### ISSUE THREAD

**Issue by Ecstasyyy1337** [HerrEurobeat/steam-comment-service-bot#100]
I have 12 unlimited steam accounts created last week by me, deposited 5€ on each and enabled email steam guard. Everytime I need to add(friend requests) the bots on the account I want to comment, if I do not I get this error “The settings on this account do not allow you to add comments” 

![](https://media.discordapp.net/attachments/854489684221362176/854496528429613056/unknown.png)

Also if you know where to buy cheap Unlimited accounts and add me here Ecstasyyy.#0001 because I want to talk more to you and buy. Thank you!

**Comment by Ecstasyyy1337** [comment]
Ecstasyyy. # 0001

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  
This seems more like an "issue" with Steam than with my bot.  
Have you tried commenting manually on the profile with one of your bot accounts? Does that work?  
Have you made sure that the profile that you are trying to comment on has their comment section set to public?  

Trying to figure out what causes those Steam Errors is always a pain in the butt because Steam doesn't provide documentation about them (or I haven't been able to find them(?)).  
The error from your screenshot above can also be just a cooldown error - the only way to find out is to try out different things sadly. But as soon as you found the right config values and your accounts are commenting fine the bot works really reliable (I'm actually surprised myself how little errors I get with my 24/7 hosted bot).  

Regarding buying accounts - sorry I don't have any idea. I have never bought accounts myself.

**Comment by Ecstasyyy1337** [comment]
> Hey, thanks for opening an issue.
> This seems more like an "issue" with Steam than with my bot.
> Have you tried commenting manually on the profile with one of your bot accounts? Does that work?
> Have you made sure that the profile that you are trying to comment on has their comment section set to public?
> 
> Trying to figure out what causes those Steam Errors is always a pain in the butt because Steam doesn't provide documentation about them (or I haven't been able to find them(?)).
> The error from your screenshot above can also be just a cooldown error - the only way to find out is to try out different things sadly. But as soon as you found the right config values and your accounts are commenting fine the bot works really reliable (I'm actually surprised myself how little errors I get with my 24/7 hosted bot).
> 
> Regarding buying accounts - sorry I don't have any idea. I have never bought accounts myself.

So it works to comment manually but I do not know why with the app I’m getting this error if the user is not my friend, I tought its an issue maybe by the config or idk, can you help me in DM? I pay you

**Comment by Ecstasyyy1337** [comment]
Or after I make the account unlimited(deposit 5€), I need to do anything more? I also did tasks on all for level 1.

**Comment by Ecstasyyy1337** [comment]
I know you have a 24/7 bot but users needs to add him in order to give him a command then he comments on your profile so he is your friend at that moment, have you tried to comment non friend users?

**Comment by HerrEurobeat** [comment]
> So it works to comment manually but I do not know why with the app I’m getting this error if the user is not my friend, I tought its an issue maybe by the config or idk, can you help me in DM? I pay you

Sure but no need to pay. Donations are always appreciated (this repository has a Sponsor button at the top) but I don't expect them.  
I don't think it is a problem with the config if you can't comment at all with the accounts through the bot. Although it is also weird if  you can comment manually with them since this is a error returned by Steam. If you can comment with the accounts through the bot but just not all the time then it is probably a cooldown and can be mitigated by tweaking config values.

**Comment by HerrEurobeat** [comment]
> Or after I make the account unlimited(deposit 5€), I need to do anything more? I also did tasks on all for level 1.

That should be fine. If you can increase the level of an account then it has to be unlimited iirc

**Comment by HerrEurobeat** [comment]
> I know you have a 24/7 bot but users needs to add him in order to give him a command then he comments on your profile so he is your friend at that moment, have you tried to comment non friend users?

You have to do that because my accounts are limited and I didn't want to spend 5€ for all of them.  

But I think I heard somewhere that you will get cooldowns quicker for accounts that aren't on your friend list so adding them is definitely a good idea. Since your accounts are unlimited you can use the `!addfriend` command with the bot to send friend requests if you wish.  
(I also read once that you can only comment a few times in total on a non friend account but I have no idea if that is true but I don't think so - I just think you will get a cooldown quicker)

**Comment by Ecstasyyy1337** [comment]
> > I know you have a 24/7 bot but users needs to add him in order to give him a command then he comments on your profile so he is your friend at that moment, have you tried to comment non friend users?
> 
> You have to do that because my accounts are limited and I didn't want to spend 5€ for all of them.
> 
> But I think I heard somewhere that you will get cooldowns quicker for accounts that aren't on your friend list so adding them is definitely a good idea. Since your accounts are unlimited you can use the `!addfriend` command with the bot to send friend requests if you wish.
> (I also read once that you can only comment a few times in total on a non friend account but I have no idea if that is true but I don't think so - I just think you will get a cooldown quicker)

I cant even do 1 single comment, its not a cooldown problem

**Comment by Ecstasyyy1337** [comment]
Can maybe be a verification issue by your bot since you add all people that you want to get commented? or what steam issue could be?

**Comment by HerrEurobeat** [comment]
tbh I don't really have any idea what could cause this except from cooldowns or just no permission to comment on that profile.  
In theory this issue should also occur when trying to comment manually.  

Could you maybe try what happens when you unfriend the bot and try to request comments for yourself? Maybe I broke something with the commenting on another profile id but if it works when being friend with the other account I don't think that this is the problem.  

Does this error also occur when trying to comment on other profiles? (I guess you already tested that but just want to ask)  

Steam errors are sadly trial and error and it happened often that I discovered new quirks when I made this project.

**Comment by Ecstasyyy1337** [comment]
Does this error also occur when trying to comment on other profiles? (I guess you already tested that but just want to ask)


> Yes, it does on any profile if that user is not in my friendlist!

Can you also make me a command to insert quotes by steam message? And how I can add multiple owners

**Comment by HerrEurobeat** [comment]
A custom quote selection from the steam chat is already possible. Check the docs for the comment command: https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Commands-documentation  

Adding multiple owners is also easy. Take a look at the `ownerid` key in the config documentation: https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Config-documentation  

Regarding the comment error I sadly have no idea. It is Steam that denies your request to post a comment and _probably_ has nothing to do directly with my code, although it is weird if you say that you can comment manually.  
I'll test it in the future with my secondary Steam account (which is unlimited) if there is something behaving wrong in my code.

**Comment by Ecstasyyy1337** [comment]
I suggest you unfriend someone then try from your unlimited account !comment 1 “profile” so you can check if your bot is working.
Also I did not understand how to insert custom quotes, I want the messages, the comments that I comment on people’s profile to be inserted trough steam chat.
I want to talk more with you in Private.. can we do that? I’m interested in buying the bot and you remove your name anywhere its written if you can, also if the bot can be used as a discord bot.

**Comment by Ecstasyyy1337** [comment]
Also I want to ask where you host your bot to be 24/7, I tried on heroku and it doesnt work

**Comment by HerrEurobeat** [comment]
> I suggest you unfriend someone then try from your unlimited account !comment 1 “profile” so you can check if your bot is working.  
Yeah thats what I planned to do but I'm working on another project rn  

> Also I did not understand how to insert custom quotes, I want the messages, the comments that I comment on people’s profile to be inserted trough steam chat.  
Yes, the bot will use the custom quotes to comment instead of your `quotes.txt`. 
Example to comment either `Message 1`, `Message 2` or `Message 3` 10 times (quote is random every time) on my profile:  
`!comment 10 76561198260031749 ["Message 1", "Message 2", "Message 3"]  

The custom quotes parameter basically overwrites your `quotes.txt` quote selection and chooses randomly just from the few you provided in the Array.  

> I want to talk more with you in Private.. can we do that?  
Sure, add me on Discord `3urobeat#0975`.  

> I’m interested in buying the bot and you remove your name anywhere its written if you can  
Not sure if I wanna do that  

> also if the bot can be used as a discord bot.  
Not directly but you can integrate the bot into a Discord bot. Read here for more info: https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Integrating-into-your-own-application  

> Also I want to ask where you host your bot to be 24/7, I tried on heroku and it doesnt work  
I host my stuff myself on a Raspberry Pi 3B at home
