### ISSUE TITLE
[Help] Keeps getting errors in commenting

### ISSUE THREAD

**Issue by SENPAY98K** [HerrEurobeat/steam-comment-service-bot#111]
## Describe the bug
I requested 15 comments to a friend profile which was not a friend with my accountBots (all unlimited)..
Then I reseted the cooldown and requested 10 comments on my profile (all bots are friended), and i got same error.

## Additional infos
> !failed: ↓

Your last request for '76561198097242611' from '2021-07-19 04:04:33' (GMT time) had these errors:

{
"Comment 7 (bot6)": "postUserComment error: Error: The settings on this account do not allow you to add comments. [Please wait a moment and try again!]",
"Comment 8 (bot7)": "postUserComment error: Error: The settings on this account do not allow you to add comments. [Please wait a moment and try again!]",
"Comment 9 (bot8)": "postUserComment error: Error: The settings on this account do not allow you to add comments. [Please wait a moment and try again!]",
"Comment 10 (bot9)": "postUserComment error: Error: The settings on this account do not allow you to add comments. [Please wait a moment and try again!]",
"Comment 11 (bot10)": "postUserComment error: Error: The settings on this account do not allow you to add comments. [Please wait a moment and try again!]",
"Comment 12 (bot11)": "postUserComment error: Error: The settings on this account do not allow you to add comments. [Please wait a moment and try again!]",
"Comment 13 (bot12)": "postUserComment error: Error: The settings on this account do not allow you to add comments. [Please wait a moment and try again!]",
"Comment 14 (bot13)": "postUserComment error: Error: The settings on this account do not allow you to add comments. [Please wait a moment and try again!]",
"Comment 15 (bot14)": "postUserComment error: Error: The settings on this account do not allow you to add comments. [Please wait a moment and try again!]"
}

## Full error
![image](https://user-images.githubusercontent.com/77079047/126101488-90882ebc-bd44-472b-9730-ef3f166c5ff4.png)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue and the detailed description!  

Unfortunately this doesn't look like a bug in my code but more like an intended response from Steam. Since Steam doesn't provide descriptions what causes which error and also behaves quite random sometimes, this can have multiple causes.  

Have you made sure your bot accounts fulfill Steam's limitations for commenting? (At least E-Mail Steam Guard, must be friend with receiving profile if account is limited)  
It also seems to help being friend with the receiving account even if your bot account is unlimited.  

This error can also be caused when the receiving profile blocked your bot account or has their comment section on private.  

Last but not least this can also just be a cooldown error. Either your accounts have commented to often in a short time period or the receiving comment section has gotten too many comments in the last short time period.  
Make sure your commentdelay is not too low to avoid getting cooldown errors often in general.  
  
Sorry for not being able to give a more detailed explanation what the issue might be but Steam sometimes behaves randomly and also provides no documentation as they don't want to support bots on their platform. This means that basically everything is reverse engineered and based on trying out and finding out what might cause what.
