### ISSUE TITLE
Comment without add

### ISSUE THREAD

**Issue by alexandrubo** [HerrEurobeat/steam-comment-service-bot#122]
Hello,i want to give someone comments without adding the bots,is that posible?

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
In order to comment on a non-friend profile your bot accounts need to be unlimited (aka they need to spend at least $5 in the Steam Store). This is a limitation by Steam.  
You can check all limitations on their support page: https://help.steampowered.com/en/faqs/view/71D3-35C2-AD96-AA3A  
   
Note: This is also explained in the README.md at the bottom: https://github.com/HerrEurobeat/steam-comment-service-bot#steam-limitations

**Comment by HerrEurobeat** [comment]
Since you didn't reply I am going to close this issue and I hope this answered your question.
If not feel free to reopen this issue or if you've got another question or anything else feel free to open another issue.
