### ISSUE TITLE
Ussage: Owner only / Dont accept friend requests

### ISSUE THREAD

**Issue by DrunkenBlyatHvH** [HerrEurobeat/steam-comment-service-bot#123]
Can i just turn off accepting friend request and set all commands to owner only ?

**Comment by HerrEurobeat** [comment]
Take a look at the config documentation: https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Config-documentation  
You can set `allowcommentcmdusage` to false so that only owners can request comments.  
However the bot will still accept friend requests.  

I'll take note and add an option in version 2.12 to disable friend requests aswell when the `advancedconfig.json` will come.

**Comment by DrunkenBlyatHvH** [comment]
> 
already did anyway thanks
