### ISSUE TITLE
problem with launching more than 10 commenting accounts?

### ISSUE THREAD

**Issue by hoost1k1337** [HerrEurobeat/steam-comment-service-bot#126]
Hello friend, I'm facing such a problem when I want to get 20 comments with the command !comment 20

![89LnUP7Cyxk](https://user-images.githubusercontent.com/103311428/162566681-d0b3683a-04ff-4a06-aa36-ba4a3e276a23.jpg)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
It seems like you are running into an IP cooldown error because you are trying to comment too often in a short time span from the same IP.  
This is intended behavior from Steam (and most services on the Internet) to limit the amount of requests from an IP so that it can't spam requests and flood their servers.  
  
You have three options to try preventing this from happening:  
- Request less often less comments (worst option)  
- Increase commentdelay significantly (best option if you don't want to buy proxies)
- Buy a few proxies to spread the requests to multiple IP addresses (best option, can definitely recommend)  
  
I am using 33 proxies with my 37 bot accounts, paying $1 per month and have set the commentdelay to 5000.  
Commenting 111 times on my profile in ~9 minutes without issues.

**Comment by hoost1k1337** [comment]
Thanks for the answer, can you tell me where to buy working http proxies?

**Comment by HerrEurobeat** [comment]
No problem! I got mine from https://www.webshare.io/
