### ISSUE TITLE
 Error: The specified profile could not be found.

### ISSUE THREAD

**Issue by nevilss** [HerrEurobeat/steam-comment-service-bot#130]
![image](https://user-images.githubusercontent.com/37747962/174789067-419cbccd-dcb8-4ed2-aacd-c5a18dd7f1bb.png)

Please help  Error: The specified profile could not be found.

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  
Profile links using the `/profiles/steamID64` style don't seem to get recognized as valid in version 2.11.  
This seems to be fixed already in the latest beta version of 2.12.  
  
For now, if you can, use a `/id/customName` styled link.  
Since that link and ownerid in your screenshot don't seem to be your "real" account anyway, you should use this link and id:  
`https://steamcommunity.com/id/Vaccolva`  
`76561198243450780`

**Comment by HerrEurobeat** [comment]
Since you didn't reply I am going to close this issue and I hope this answered your question.
If not, feel free to reopen this issue or please create another issue if there is something else on your mind!
