### ISSUE TITLE
InvalidParam while trying to get a new session

### ISSUE THREAD

**Issue by yourfanboy** [HerrEurobeat/steam-comment-service-bot#148]
Hello, I got some troubles using bot. Hope someone will help me.

**Describe the bug**
Getting an error while trying to login on acc with correct credentials. With proxy and without proxy.

**Full error**
[2023-03-02 19:56:48 | WARN] [Main] Error: InvalidParam while trying to get a new session for 'mainacc' using login credentials. Retrying login in 5 seconds...

**Additional context**
Using node v18.14.2

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue and sorry that I wasn't able to reply sooner!  
As @LesikEdelweiss already discovered this seems to be fixed by updating `steam-session` to the latest version.  

I'm going to merge #150 and publish Version 2.12.3. Your bot should automatically update to the newest version the next time you start it.
