### ISSUE TITLE
https://prnt.sc/gNzStmOkwDDE error

### ISSUE THREAD

**Issue by PlueTah** [HerrEurobeat/steam-comment-service-bot#177]
**Describe the bug**
A clear description of what you did and what happened.

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.

I want to post many rate up at once

**Comment by HerrEurobeat** [comment]
Hey, can you show me the output of `!sessions`?

**Comment by HerrEurobeat** [comment]
Looks like you started a vote request with all accounts and you need to wait until it and its cooldown is done before requesting votes for another item.  
This is to avoid cooldowns because your accounts might vote too quickly on too many items.  
If you don't want that you can always change the `commentcooldown` & `botaccountcooldown` settings in your `config.json`. All request types (comments, votes & favs) currently use the same setting, I might change that in the future but it should be fine for now.  
  
There is however a bug in your second screenshot, it should say "66 votes with 66 accounts...", I'm going to fix that in a few minutes, thanks for letting me know lol

**Comment by PlueTah** [comment]
ok thanks for all

**Comment by HerrEurobeat** [comment]
Update 2.13 is coming out today btw, I'm currently writing the patchnotes

**Comment by PlueTah** [comment]
btw, the system works very well.

**Comment by HerrEurobeat** [comment]
Version 2.13 is out on master.  
Check out the release notes [here](https://github.com/HerrEurobeat/steam-comment-service-bot/releases/tag/2.13.0)!
