### ISSUE TITLE
Bots

### ISSUE THREAD

**Issue by DennisMariquit** [HerrEurobeat/steam-comment-service-bot#33]
Hello does this need all bots to be nonlimited or is there anyway to make my main acct add those bots automatically and then send comments on main then unfriend

**Comment by HerrEurobeat** [comment]
Hi, thanks for opening an issue.
It depends on what you want to achieve. Of course you can use all accounts limited if you are friends with all of them. 
Even if your accounts are unlimited you can still run into errors because steam only allows a few comments on non friend profiles with unlimited accounts.

The next feature update (2.7) will return a list of profile links to the user to add the accounts if they are limited.
I'm not sure what you mean with:
> make my main acct add those bots automatically and then send comments on main then unfriend

Do you mean with main your bot0 or your requesting account? If you mean bot0, no that account can't send friend requests for other accounts - that is just impossible. 
If you mean your requesting account you can just add them. They will accept automatically and then request comments.

**Comment by DennisMariquit** [comment]
bot0=main
bot(x)= all other limited bots
bot0 will add all the bot(x) then bot(x) will confirm then send comments to bot0

**Comment by HerrEurobeat** [comment]
Oh thats not how it works.
bot0 is the steam account you will message with !comment to request a comment.
The bot0 will then start the comment process of all other accounts.

That means that your account (the requesting account) needs to be friend with all **limited** accounts. The bot0 account is just the account that interacts with the user etc.

**Comment by DennisMariquit** [comment]
ohh so you need manually add those limited that might take a while 😉
