### ISSUE TITLE
The settings on this account do not allow you to add comments

### ISSUE THREAD

**Issue by gokhannguneey** [HerrEurobeat/steam-comment-service-bot#34]
hi  i try to send comment and i got a this error pls help me 

[https://prnt.sc/sr4os7](url)

**Comment by gokhannguneey** [comment]
The settings on this account do not allow you to add comments
https://prnt.sc/sr4os7

**Comment by HerrEurobeat** [comment]
Hi, thanks for opening an issue.
As I wrote (here)[https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Errors,-FAQ-&-Common-problems#steam-errors] this can be caused because of steam's limitations:
> The profile's comment section you are trying to comment on is private or your account doesn't meet steams regulations. Read more about steam limitations: [Click](https://github.com/HerrEurobeat/steam-comment-service-bot#steam-limitations)

Make sure that you have read the `Steam limitations` part [here](https://github.com/HerrEurobeat/steam-comment-service-bot#steam-limitations).

If you are sure that the errors are not being caused because of the described limitations then it could also be very well a random error.  
I am getting these as well from time to time but it works fine for me after trying again.

Also - since this is a steam error - I am sadly unable to do anything against it because it is being thrown by steam and not from my bot.
I hope this helps.

**Comment by HerrEurobeat** [comment]
Since you didn't reply I assume that it is working now.
If this problem is still present, feel free to just comment again.
If you encounter another problem/error/bug, please open another issue.
Thanks!
