### ISSUE TITLE
Half of the accounts loaded up ... the others gone... 

### ISSUE THREAD

**Issue by legasto588** [HerrEurobeat/steam-comment-service-bot#39]
so basically i've added about 10 account into logininfo.json

loaded up... only 5 of them appear on the window shell... the others gone.. 
any idea? 

checked all my commas,password,accs,steamguard enabled,etc everything completely ready but
its does not appear on window shell..

**Comment by HerrEurobeat** [comment]
Hi, thanks for opening an issue!
Have you got any other information? This problem sounds really weird...

What do you mean with 'gone'? Are the accounts still in your logininfo?
Have you extended your logininfo.json correctly?
```
{
	"bot0": ["username0", "password0"],
	"bot1": ["username1", "password1"],
	"bot2": ["username2", "password2"],
	"bot3": ["username3", "password3"],
	"bot4": ["username4", "password4"],
	"bot5": ["username5", "password5"],
	"bot6": ["username6", "password6"],
	"bot7": ["username7", "password7"]
}
```

What does your console log say?
Any errors?

**Comment by legasto588** [comment]
it says nothing . it just do nothing 
![Capture](https://user-images.githubusercontent.com/66567658/83977335-6ec3b500-a932-11ea-8b5e-da3875ee5715.PNG)

**Comment by legasto588** [comment]
yea i 've extended my configlogin just like the above ..... btw do i need to enter steam guard code ? maybe it can help process to other 5 account?

**Comment by HerrEurobeat** [comment]
Well that explains why your accounts don't show up :D 
Yes, in order to be even able to login your accounts you must type in your steam guard code. The purpose of a steam guard code is to protect your account so that an unknown person can't get your account that easily - even if he/she has your username and password.

If you type in the steam guard codes (which you should get via email) for each account (you only need to do this once for each account) then you should be good to go.

**Comment by HerrEurobeat** [comment]
Hey, is it working for you now?

**Comment by legasto588** [comment]
yeap its working perfectly fine.. thanks!
