### ISSUE TITLE
Child Bots

### ISSUE THREAD

**Issue by steel4me** [HerrEurobeat/steam-comment-service-bot#41]
**Describe the solution you'd like**
https://github.com/HerrEurobeat/steam-comment-service-bot/projects/2#card-37291595

**Additional context**
Does this mean that child bots automaticly accepting friend requests?
Or a further brainstorming. Is it possible that child bots send friend request automaticly?

**Comment by steel4me** [comment]
Okay, sorry, child bots automaticly add friends.

**Comment by HerrEurobeat** [comment]
Hey, no worries.
Just for clarification: Every bot always accepts friend requests. If you add a child bot and message it, the bot will just respond with a reference to the main bot's profile. 

The project card you linked will be a feature integrated in version 2.7 that will message the user all profile links of bot accounts that would be used for the requested amoun of comments, are limited and not friend with the user.
The second feature will be a check if a non limited account that is also not friend with the user throws a specific error. If this happens the user will recieve a message that he should add these accounts in order to prevent further cooldown errors. I hope that clarifies it :)

And thank you for the 5€ donation! Really appreciate it!

**Comment by steel4me** [comment]
once you've started coding something like your bot, you can't stop coding, I know that. the donation is for sharing the bot with us via github, thats really great!

I already cloned the 2.7 b3 from branch beta-testing and got !info error again but cannot reproduce it :)

**Comment by HerrEurobeat** [comment]
Yeah the !info failcheck will be included in b4. I hope I can finally push b4 in the next days but I'm currently experiencing bugs that are crashing the bot randomly which I need to fix before pushing it.

I also changed the updater a bit so that if you download a beta version it should check if there is a new beta build available and be able to download it.

**Comment by steel4me** [comment]
Really cool, you answered a question that i still wanted to ask, are you secretly traveling through time?
Sure, it's done when it's done ;)

**Comment by HerrEurobeat** [comment]
Hey, just wanted to let you know that the beta build b4 is now out!
It took longer than expected but I had to fix a few bugs and it has quite a lot of changes. It should now also be able to update to a newer beta version if available.
