### ISSUE TITLE
 Unexpected token in JSON at position 55

### ISSUE THREAD

**Issue by panfb** [HerrEurobeat/steam-comment-service-bot#44]
hello firstly when i wrote npm install it gave the error in 1st screensho
![firsterr](https://user-images.githubusercontent.com/67068139/84927585-b9cd8d00-b0d5-11ea-8f25-0fc043f85978.png)
![error2](https://user-images.githubusercontent.com/67068139/84927609-bf2ad780-b0d5-11ea-910a-9a7f9f1141c0.png)

t and when i wrote node start.js, i gave the error in 2nd screenshot please can you help

**Comment by HerrEurobeat** [comment]
Hi, thanks for opening an issue.
The first error is node/npm related. Since those are not my work and I haven't ever had a node/npm error I can only suggest that you maybe reinstall node.js and try `npm install` again.

Concerning the second error (and assuming it's not caused by the the first error) you seem to have made a mistake in your `logininfo.json` syntax.
Please make sure that your `logininfo.json` follows exactly this pattern:

```
{
	"bot0": ["username0", "password0"],
	"bot1": ["username1", "password1"],
	"bot2": ["username2", "password2"]
}
```

Your usernames and passwords need to be inside the quotes ("). Please make sure this is the case.

**Comment by HerrEurobeat** [comment]
I assume that the heart means that it solved the problem. If that's the case I'm glad I could help.
If this error/problem still persists then please reopen the issue.
Thanks!
