### ISSUE TITLE
i need convert account file to json formate

### ISSUE THREAD

**Issue by ilovegame1985** [HerrEurobeat/steam-comment-service-bot#60]
hello sir
i have account file in this format :- attlesnakel3135foster:YUAROF1DGGY0832

need to convert this format:- "bot0": ["username0", "password0", "shared_secret"],

please share any script for this

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!
Since version 2.9 you can also use accounts with the format you used. Create a `accounts.txt` file in your `steam-comment-service-bot` folder and put an account with the `username:password` format in each line.

This feature is also documented in the README.md under the "Accounts" column.

**Comment by ilovegame1985** [comment]
thank you so much sir
