### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by profilenamee** [HerrEurobeat/steam-comment-service-bot#68]
**Error/Element that doesn't work**
Please include the full error you get or if you get none, describe precisely what happened.

**Additional information**
![Screenshot_7](https://user-images.githubusercontent.com/76629600/103158411-7f7f2f80-478b-11eb-8868-d6fe166dd205.png)
![Screenshot_8](https://user-images.githubusercontent.com/76629600/103158412-8148f300-478b-11eb-9028-967e408e2445.png)

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  

This error is caused most of the time when the profile's comment section you are trying to comment on is private, your account doesn't meet steams regulations, or the recieving profile has recieved too many comments in the last hours.  
In some cases this error can also occur when the bot's accounts got a cooldown because they commented too often recently and can only be solved by waiting for roughly 1-3 hours.  

Since you are using my bot (from looking at the screenshots) just wait a bit and try again, the last successful comment was at 16:13 (GMT) right now and the last request (which failed) at 18:04 (GMT).
