### ISSUE TITLE
postUserComment error: Error: HTTP error 429

### ISSUE THREAD

**Issue by notevenftw** [HerrEurobeat/steam-comment-service-bot#71]
hi, i got this [error](https://prnt.sc/wywsww)

the bot accounts are only a few days old, and 3 of them are limited, is this the cause? 

the user had all the bots added, so i thought that there would not be comment limitations

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  
The error you got is a cooldown error as documented [here](https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Errors,-FAQ-&-Common-problems#steam-errors). You need to add limited accounts in order to even be able to comment but adding them doesn't exclude them from getting cooldowns by commenting too often.

**Comment by HerrEurobeat** [comment]
I hope my response helped.  
If your question still persists just reopen the issue again. If you have another question just open another issue. Thanks!
