### ISSUE TITLE
using with ArchiSteamFarm

### ISSUE THREAD

**Issue by notevenftw** [HerrEurobeat/steam-comment-service-bot#74]
hi! is there currently a way to use the bot with ASF (archisteamfarm)?

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  
I'm actually not sure but I think as long as you haven't set a game in the config it shouldn't block ASF.  
I have never tried it but I would assume it is possible to run both at the same time because using your Steam Client is also possible when ASF is running.  
But I don't see a way to use the comment bot as a "plugin" for ASF if that is what you mean.  
Have you tried running both at once?

**Comment by notevenftw** [comment]
hey thankyou for the reply! it gives me error: LoggedInElsewhere

**Comment by HerrEurobeat** [comment]
Hm well then it seems like ASF is logging into SteamCommunity, which my Comment Bot also needs to do and a user can only be logged in into SteamCommunity once.  
Are you maybe still running the Steam Client? I'm not sure if ASF actually logs into SteamCommunity.

**Comment by notevenftw** [comment]
ahh okay I get it. thankyou! 
by chance do you know a way to run the bot even while my computer is off? or if my internet drops? is that possible?

**Comment by HerrEurobeat** [comment]
The bot will only run if the device is on & has internet. (no magic lol)  
You could buy/rent a server or look for a free hosting service like heroku or Amazon AWS or buy a Raspberry Pi to host things on 24/7 with very small power draw (like I did).

**Comment by PanSmuggler** [comment]
> The bot will only run if the device is on & has internet. (no magic lol)
> You could buy/rent a server or look for a free hosting service like heroku or Amazon AWS or buy a Raspberry Pi to host things on 24/7 with very small power draw (like I did).

I'm using repl.it to host bot but the problem is that you need shared secret because it doesn't have static ip...
