### ISSUE TITLE
Error loading lastcomment.db 

### ISSUE THREAD

**Issue by hamid-jogomba** [HerrEurobeat/steam-comment-service-bot#82]
Error loading lastcomment.db database! Error: Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
I actually haven't seen this error before so you discovered something new!  
I'm not sure if this is an error caused by a mistake in my code.  

To get this error away you can delete everything inside `lastcomment.db` in the `src` folder. This file is only used to store the last time each user requested a comment and is used to check if the bot should unfriend them or to check if they should have a cooldown applied.

**Comment by HerrEurobeat** [comment]
Nvm, a few people seem to have had this error now. I will investigate what might cause this.

**Comment by HerrEurobeat** [comment]
Update: I found out that this can be caused by a second empty line in the `lastcomment.db` file. I will implement a check for that in the next update.
