### ISSUE TITLE
User isn't getting removed from activecommentprocess correctly

### ISSUE THREAD

**Issue by Stiefel1234eu** [HerrEurobeat/steam-comment-service-bot#83]
Something is wrong with the lastcomment.db
If you request a comment and clear afterwards the cooldown the bot will still say that you are currently receiving the requested comments:
![image](https://user-images.githubusercontent.com/63855548/110986193-a3efae80-836d-11eb-9057-f46fb12ee401.png)

I have tested it also with a fresh installation

Cheers

**Comment by HerrEurobeat** [comment]
Hm good to know, thanks for reporting this issue!  
Just by looking at your screenshot this is probably not an issue with the lastcomment.db but rather with the activecommentprocess array but I don't think anyone even knows that exists. Your cooldown is getting cleared, thats why you don't get the normal cooldown message, but you aren't getting removed from the activecommentprocess array. I'm assuming right now this only happens when requesting one comment as otherwise it seems to work fine. I'll look into this and report back.  

and thanks for testing this with a fresh installation too :D

**Comment by HerrEurobeat** [comment]
Fixed in 9aaea39 (Version 2.10.2).
