### ISSUE TITLE
Bot won't start after failed update

### ISSUE THREAD

**Issue by Literaty** [HerrEurobeat/steam-comment-service-bot#86]
**Describe the bug**
A clear description of what you did and what happened.wh

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue but you need to at least provide an error in order for me to be able to help you.

**Comment by Literaty** [comment]
hey , error : https://prnt.sc/10lmwm0 steam servers

**Comment by Literaty** [comment]
new error , It came when it was an update.it was not like that before. started today. I have been using it for 6 months.

**Comment by HerrEurobeat** [comment]
Hm I think I got these errors once too and it was because of a failed update. I'm not sure (and I probably won't be able to find out) why it failed for you in this case but I think the best solution would be to reinstall the bot.  

You can keep your `logininfo.json` and quotes.txt (if you added your own comments that you don't want to loose) but you have to reconfigure your `config.json`.  

The other solution would be to go into the `src` folder, opening `data.json` and changing the version to `2.9.2` and seeing if the bot updates fine when starting.  

I'm sorry that this happened but it's also great to hear that you were using it for 6 months already :D

**Comment by Literaty** [comment]
I will try now. thanks .

**Comment by Literaty** [comment]
https://prnt.sc/10lnf0b help

**Comment by HerrEurobeat** [comment]
Yeah just delete everything inside `lastcomment.db` which is in the `src` folder.  
This seems to happen from time to time and I have no idea why yet.  
Issue: #82

**Comment by Literaty** [comment]
thanksss <3 <3< 3<3< 3<3<3<<33 <33<3<<<3<3<3<3<33< <3 <3 <3 <3<3<32<3<3<3<3e<3<w<w<3<

**Comment by HerrEurobeat** [comment]
np :)
