### ISSUE TITLE
comment limit

### ISSUE THREAD

**Issue by Stiefel1234eu** [HerrEurobeat/steam-comment-service-bot#89]
It would be nice if you could implement a request comment limit for the user.
For example:

- 20 active Bot accounts
- but user can only request 10 comments at a time

"repeatedComments" statement below 1 (e.g. 0.5 in the case above)

This would make the point "randomize accounts" more meaningful.
(not each times comments each bot)

I hope that you understand what I mean..

Cheers

**Comment by HerrEurobeat** [comment]
Thats actually something I thought about too yesterday.  
I would actually change the config values a bit and implement it a bit different.  
Maybe removing `repeatedComments` and adding `maxComments` and `ownersMaxComments` values. These would also be more descriptive in what they are doing I think.  

I think this would also include your suggestion, am I right? Because if you have 10 accounts, enable `randomizeAccounts` and set `maxComments` to like 5 then only 5 accounts would be able to comment and are randomly chosen from the 10 accounts.

**Comment by Stiefel1234eu** [comment]
Yes you understood me right :)

**Comment by HerrEurobeat** [comment]
Added in 7ca8ded (Version 2.10.4).
