### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by hyperion110** [HerrEurobeat/steam-comment-service-bot#92]
**Error/Element that doesn't work**
Please include the full error you get or if you get none, describe precisely what happened.
[05:34]
hyperion:
	!comment

[05:34]
bot1:
	Please specify how many comments out of 6 you would like to request.Command usage: '!comment number_of_comments/"all" profileid' for X many or the max amount of comments (max 6). Provide a profile id to comment on a specific profile.

[05:34]
hyperion:
	!comment 2

[05:34]
bot1:
	In order to request 2 comments you/the recieving user will first need to add this/these accounts: (limited bot accounts) ' https://steamcommunity.com/profiles/76561199156087258 '

[05:34]
hyperion:
	!comment 2

[05:34]
bot1:
	Oops, an error occurred!Please wait a moment and try again!Details: [Main] postUserComment error: Error: To post this comment, your account must have Steam Guard enabled.Last successful comment: 2021-03-29 03:29:24 (GMT time)

how fixed this?

![Uploading image.png…]()

**Additional information**
Please add any other information here if you have some.

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
As the error already says and as mentioned in the readme and YouTube video, your bot accounts need at least E-Mail Steam Guard to be able to comment on a profile. This is a limitation by Steam.  

You can enable Steam Guard by logging into the account using your browser, clicking on Account Details in the top right corner, scrolling down to Steam Guard and changing the Steam Guard to E-Mail there.  
It is important that you don't use a throwaway E-Mail for your accounts so that you can receive the Steam Guard code when logging in for the first time.

**Comment by HerrEurobeat** [comment]
Since you didn't reply I am going to close this issue and I hope this answered your question.  
If not feel free to reopen this issue or if you've got another question or anything else feel free to open another issue.
