### ISSUE TITLE
Mobile Steam Guard accounts instantly disconnect after accepting 2FA code and relog (doesn't affect E-Mail Steam Guard)

### ISSUE THREAD

**Issue by noname20214** [HerrEurobeat/steam-comment-service-bot#96]
all time when i start the bot and i put the steam guard code, log in, but in few secons dicotected by conection, after than then i need to w8 for try few times to login

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue.  
Could you please provide more information about the problem?  
It would be great if you could attach the last lines of the output.txt file (so that I can see what is happening) beginning with `Bootup sequence started...`.  

I'll assume you are running version 2.10.6. Are you using the bot for the first time or have you tried version 2.10.5 before?  
I made some changes to how disconnects and login errors are handled in this update, thats why I'm asking.

**Comment by noname20214** [comment]
its only happens with accs with steam guard (not email steam guard), im using w10, with email steam guard works fine

**Comment by noname20214** [comment]
> its only happens with accs with steam guard (not email steam guard), im using w10, with email steam guard works fine

(node:14096) Warning: Received net message from ghost connection W19 (expected W42)
[2021-05-17 22:59:00] [Bot 8] Lost connection to Steam. Reason: Error: NoConnection
[2021-05-17 22:59:00] [Bot 8] Initiating a relog in 30 seconds.

**Comment by HerrEurobeat** [comment]
Hmm interesting issue, thanks for reporting it.  
I will see if I can reproduce the behaviour on Linux and test the bot on Windows as I haven't done that in some time.  
How long do the accounts take to relog? (So basically how annoying is the issue xd)

**Comment by noname20214** [comment]
with the steam guard doesnt relog

**Comment by HerrEurobeat** [comment]
Are you still experiencing this issue?
